"""seed_mock.py — wipe domain tables and seed a procedurally-generated dataset.

DESTRUCTIVE: TRUNCATEs every domain table CASCADE before inserting.
Always run `make backup` first (Makefile wires this as a dependency).

Small static entities come from `data-migration/mock_data/*.csv`:
  branches, accounts, fee_plans, promotions, teachers, vehicles
Big tables are generated by `seed_mock_gen.py`:
  classes (102), students (~1020), payments (~1500), rentals (~120)

Run inside the backend container:
    docker compose exec backend python /app/data-migration/seed_mock.py
"""

import asyncio
import csv
import os
import random
import uuid
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

import asyncpg
import bcrypt
import sys

sys.path.insert(0, str(Path(__file__).parent))
from seed_mock_gen import (
    TIME_CUTOFF, gen_classes, gen_students, gen_payments, gen_rentals,
    gen_notifications, gen_activity_log,
)

DB_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://mgt:mgt_secret@localhost:5432/motogiathinh",
).replace("postgresql+asyncpg://", "postgresql://")

DATA_DIR = Path(__file__).parent / "mock_data"

LIC_TO_DB = {"A": "A2", "A1": "A1"}
STATUS_TO_DB = {"đang hoạt động": "active", "đang bảo trì": "maintenance"}
FEE_PLAN_TO_LICENCE = {"fee-a": "A", "fee-a1": "A1"}

random.seed(42)  # reproducible mock data across runs


def read_csv(name):
    with open(DATA_DIR / f"{name}.csv", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def truthy(s): return str(s or "").strip().lower() in ("true", "1", "yes")
def hash_pw(plain): return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


WIPE_SQL = "TRUNCATE TABLE payments, payment_plans, class_enrollments, notifications, audit_logs, student_contacts, students, classes, course_types, vehicles, promotions, fee_plans, instructors, branches, users RESTART IDENTITY CASCADE"


# ── Small static seeders (from CSV) ──────────────────────────────────────────

async def seed_branches(conn, id_map):
    rows = read_csv("branches")
    for r in rows:
        uid = uuid.uuid4()
        id_map["branches"][r["id"]] = uid
        await conn.execute(
            """INSERT INTO branches (id, ma_chi_nhanh, ten_chi_nhanh, dia_chi, is_active,
                slug, created_at, updated_at)
               VALUES ($1, $2, $3, $4, TRUE, $5, NOW(), NOW())""",
            uid, r["id"].upper().replace("-", ""), r["name"],
            r.get("address") or None, r["id"],
        )
    print(f"  branches: {len(rows)}")


PERMISSION_RESOURCES = [
    "students", "payments", "classes", "branches", "accounts",
    "vehicles", "teachers", "fee_plans", "promotions", "activity_log",
]


async def seed_users(conn, id_map):
    rows = read_csv("accounts")
    pw = hash_pw("admin")
    for r in rows:
        uid = uuid.uuid4()
        id_map["users"][r["id"]] = uid
        branch_uuid = id_map["branches"].get(r.get("branchId")) if r.get("branchId") else None
        eff_branch = None if r["role"] == "admin" else branch_uuid
        await conn.execute(
            """INSERT INTO users (id, email, phone, password_hash, full_name, role,
                branch_id, is_active, is_verified, created_at, updated_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, TRUE, NOW(), NOW())""",
            uid, r["email"], r.get("phone") or None, pw, r["name"],
            r["role"], eff_branch, truthy(r.get("active")),
        )
        # Permissions backfill: admin role bypasses but we still insert
        # all-true rows for UI symmetry. Huy keeps activity_log all-false
        # (preserves the "restricted staff" demo case from prior phases).
        for res in PERMISSION_RESOURCES:
            is_huy_audit = (r["email"] == "huy@motogiathinh.vn" and res == "activity_log")
            cr, rd, up, dl = (False, False, False, False) if is_huy_audit else (True, True, True, True)
            await conn.execute(
                """INSERT INTO user_permissions
                     (id, user_id, resource, can_create, can_read, can_update, can_delete,
                      created_at, updated_at)
                   VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, NOW(), NOW())
                   ON CONFLICT (user_id, resource) DO NOTHING""",
                uid, res, cr, rd, up, dl,
            )
    # branches.manager_id patch
    for r in read_csv("branches"):
        m = id_map["users"].get(r.get("manager_id")) if r.get("manager_id") else None
        if m:
            await conn.execute("UPDATE branches SET manager_id=$1 WHERE id=$2",
                               m, id_map["branches"][r["id"]])
    print(f"  users: {len(rows)}")


async def seed_teachers(conn, id_map):
    rows = read_csv("teachers")
    pw = hash_pw("teacher")
    for r in rows:
        ghost = uuid.uuid4()
        branch_uuid = id_map["branches"].get(r.get("branchId"))
        await conn.execute(
            """INSERT INTO users (id, email, password_hash, full_name, role, branch_id,
                is_active, is_verified, created_at, updated_at)
               VALUES ($1, $2, $3, $4, 'staff', $5, FALSE, TRUE, NOW(), NOW())""",
            ghost, f"{r['id']}@teachers.motogiathinh.local", pw, r["name"], branch_uuid,
        )
        instr = uuid.uuid4()
        id_map["teachers"][r["id"]] = instr
        try: years = int(r.get("yearsExp") or 0)
        except ValueError: years = 0
        hired = date(date.today().year - years, 1, 1)
        await conn.execute(
            """INSERT INTO instructors (id, branch_id, user_id, ma_giao_vien, ho_ten,
                so_dien_thoai, ngay_vao_lam, is_active, rating_avg, total_reviews,
                created_at, updated_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, TRUE, 0, 0, NOW(), NOW())""",
            instr, branch_uuid, ghost, r["id"].upper(), r["name"],
            r.get("phone") or "", hired,
        )
    print(f"  teachers + ghost users: {len(rows)}")


async def seed_vehicles(conn, id_map):
    rows = read_csv("vehicles")
    vehicles_out = []
    for r in rows:
        uid = uuid.uuid4()
        branch_uuid = id_map["branches"].get(r.get("branchId"))
        if not branch_uuid:
            continue
        licence_wire = r.get("licence") or "A1"
        loai = LIC_TO_DB.get(licence_wire, "A1")
        status = STATUS_TO_DB.get((r.get("status") or "").lower(), "active")
        try: year = int(r.get("year") or 0) or None
        except ValueError: year = None
        rental_price = Decimal(50000)
        await conn.execute(
            """INSERT INTO vehicles (id, branch_id, bien_so, loai_xe, ten_xe, nam_san_xuat,
                loai_bang_lai, trang_thai, odometer_km, last_service_km, rental_price,
                created_at, updated_at)
               VALUES ($1, $2, $3, 'motorbike', $4, $5, $6, $7, 0, 0, $8,
                       NOW(), NOW())""",
            uid, branch_uuid, r["plate"], r["name"], year, loai, status, rental_price,
        )
        vehicles_out.append({
            "id": uid, "branch_id": branch_uuid,
            "rental_price": rental_price, "licence_wire": licence_wire,
        })
    print(f"  vehicles: {len(vehicles_out)}")
    return vehicles_out


async def seed_fee_plans(conn):
    rows = read_csv("fee_plans")
    out = {}
    for r in rows:
        uid = uuid.uuid4()
        amount = Decimal(r["amount"])
        await conn.execute(
            """INSERT INTO fee_plans (id, name, licence, amount, created_at, updated_at)
               VALUES ($1, $2, $3, $4, NOW(), NOW())""",
            uid, r["name"], r["licence"], amount,
        )
        out[r["licence"]] = (uid, amount)
    print(f"  fee_plans: {len(rows)}")
    return out


async def seed_promotions(conn):
    rows = read_csv("promotions")
    by_licence = {"A": [], "A1": []}
    for r in rows:
        uid = uuid.uuid4()
        raw = r.get("appliesTo_csv") or ""
        applies = [FEE_PLAN_TO_LICENCE.get(x.strip(), x.strip())
                   for x in raw.split("|") if x.strip()] or ["A", "A1"]
        applies = [a for a in applies if a in ("A", "A1")]
        discount = Decimal(r.get("discount") or 0)
        await conn.execute(
            """INSERT INTO promotions (id, ma_khuyen_mai, ten_khuyen_mai, loai_khuyen_mai,
                gia_tri, is_active, is_partner, applies_to_csv, created_at, updated_at)
               VALUES ($1, $2, $3, 'fixed', $4, TRUE, FALSE, $5, NOW(), NOW())""",
            uid, r["id"].upper().replace("-", ""), r["name"], discount, "|".join(applies),
        )
        for lic in applies:
            by_licence[lic].append((uid, discount, r["name"]))
    print(f"  promotions: {len(rows)}")
    return by_licence


async def seed_course_type(conn):
    ct_id = uuid.uuid4()
    await conn.execute(
        """INSERT INTO course_types (id, ma_khoa_hoc, ten_khoa_hoc, loai_bang_lai,
            so_buoi_ly_thuyet, so_buoi_thuc_hanh, tong_gio_hoc, thoi_gian_dao_tao,
            hoc_phi, phi_thi, phi_sat_hach, tuoi_toi_thieu, is_active,
            created_at, updated_at)
           VALUES ($1, 'KH-MOTO', 'Mô tô', 'A1', 8, 12, 80, 60,
                   0, 0, 0, 18, TRUE, NOW(), NOW())""", ct_id,
    )
    return ct_id


# ── Bulk inserts for generated data ─────────────────────────────────────────

async def insert_classes(conn, classes):
    for c in classes:
        await conn.execute(
            """INSERT INTO classes (id, branch_id, ma_lop, ten_lop, course_type_id,
                ngay_khai_giang, ngay_ket_thuc, so_luong_toi_da, so_luong_hien_tai,
                trang_thai, created_at, updated_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, 30, 0, 'in_progress', NOW(), NOW())""",
            c["id"], c["branch_id"], c["ma_lop"], c["ten_lop"], c["course_type_id"],
            c["ngay_khai_giang"], c["ngay_ket_thuc"],
        )
    print(f"  classes: {len(classes)}")


async def insert_students(conn, students):
    enroll_count = 0
    for i, s in enumerate(students):
        await conn.execute(
            """INSERT INTO students (id, branch_id, ma_hoc_vien, ten_hoc_vien, ngay_sinh,
                gioi_tinh, cccd_number, cccd_issued_date, cccd_issued_place,
                so_dien_thoai, dia_chi, tinh_thanh, loai_bang_lai, trang_thai,
                is_repeat_student, repeat_count, ngay_dang_ky, is_transfer,
                total_fee, fee_plan_id, promotion_id, responsible_staff_id, profile_complete,
                created_at, updated_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
                       'active', FALSE, 0, $14, FALSE, $15, $16, $17, $18, $19,
                       $20::timestamptz, $20::timestamptz)""",
            s["id"], s["branch_id"], s["ma_hoc_vien"], s["ten_hoc_vien"], s["ngay_sinh"],
            s["gioi_tinh"], s["cccd_number"], s["cccd_issued_date"], s["cccd_issued_place"],
            s["so_dien_thoai"], s["dia_chi"], s["tinh_thanh"], s["loai_bang_lai"],
            s["ngay_dang_ky"], s["total_fee"], s["fee_plan_id"], s["promotion_id"],
            s["responsible_staff_id"], s["profile_complete"], s["created_at"],
        )
        # Class enrollment
        if s.get("class_id"):
            await conn.execute(
                """INSERT INTO class_enrollments (id, class_id, student_id, enrollment_date,
                    is_active, ly_thuyet_status, thuc_hanh_status, overall_progress,
                    created_at, updated_at)
                   VALUES ($1, $2, $3, $4, TRUE, 'not_started', 'not_started', 0,
                           NOW(), NOW())""",
                uuid.uuid4(), s["class_id"], s["id"], s["ngay_dang_ky"],
            )
            await conn.execute(
                "UPDATE classes SET so_luong_hien_tai = so_luong_hien_tai + 1 WHERE id=$1",
                s["class_id"],
            )
            enroll_count += 1
        if (i + 1) % 200 == 0:
            print(f"    ... {i + 1}/{len(students)} students")
    print(f"  students: {len(students)} / enrollments: {enroll_count}")


async def insert_activity_log(conn, entries):
    for i, e in enumerate(entries):
        await conn.execute(
            """INSERT INTO audit_logs (id, user_id, branch_id, user_role, action,
                resource, resource_id, created_at, updated_at)
               VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, NOW())""",
            e["user_id"], e["branch_id"], e["user_role"], e["action"],
            e["resource"], e["resource_id"], e["created_at"],
        )
        if (i + 1) % 2000 == 0:
            print(f"    ... {i + 1}/{len(entries)} audit_logs")
    print(f"  audit_logs: {len(entries)}")


async def insert_notifications(conn, notifications):
    for n in notifications:
        await conn.execute(
            """INSERT INTO notifications (id, user_id, branch_id, title, content,
                notification_type, trigger_type, is_read, sent_at, send_status,
                entity_type, entity_id, created_at, updated_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())""",
            n["id"], n["user_id"], n["branch_id"], n["title"], n["content"],
            n["notification_type"], n["trigger_type"], n["is_read"],
            n["sent_at"], n["send_status"], n["entity_type"], n["entity_id"],
            n["created_at"],
        )
    print(f"  notifications: {len(notifications)}")


async def insert_payments(conn, payments):
    for i, p in enumerate(payments):
        await conn.execute(
            """INSERT INTO payments (id, branch_id, student_id, ma_giao_dich, so_tien,
                phuong_thuc, collected_by, collected_at, payment_status, payment_date,
                kind, vehicle_id, rental_rounds, so_bien_lai_id, created_at, updated_at)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8::timestamptz, 'paid',
                       $8::timestamptz, $9, $10, $11, $12, NOW(), NOW())""",
            p["id"], p["branch_id"], p["student_id"], p["ma_giao_dich"], p["so_tien"],
            p["phuong_thuc"], p["collected_by"], p["collected_at"], p["kind"],
            p.get("vehicle_id"), p.get("rental_rounds"), p["so_bien_lai_id"],
        )
        if (i + 1) % 500 == 0:
            print(f"    ... {i + 1}/{len(payments)} payments")
    print(f"  payments: {len(payments)}")


# ── Orchestrator ─────────────────────────────────────────────────────────────

async def main():
    print("=" * 60)
    print("SEED MOCK DATA (procedural, cutoff =", TIME_CUTOFF, ")")
    print("=" * 60)
    if not DATA_DIR.exists():
        raise SystemExit(f"Mock CSV dir not found: {DATA_DIR}")

    conn = await asyncpg.connect(DB_URL)
    try:
        print("Wiping domain tables ...")
        await conn.execute(WIPE_SQL)

        id_map = {"branches": {}, "users": {}, "teachers": {}}
        await seed_branches(conn, id_map)
        await seed_users(conn, id_map)
        await seed_teachers(conn, id_map)
        vehicles = await seed_vehicles(conn, id_map)
        fee_plans_by_licence = await seed_fee_plans(conn)
        promos_by_licence = await seed_promotions(conn)
        course_type_id = await seed_course_type(conn)

        # Branch + staff maps for generation. Both 'staff' and 'user' roles
        # can be responsibleStaffId on students (user is just a more
        # restricted variant of staff with no Tổ chức edit + filtered audit).
        branch_uuids = list(id_map["branches"].values())
        staff_by_branch = {bid: [] for bid in branch_uuids}
        rows = read_csv("accounts")
        for r in rows:
            if r["role"] not in ("staff", "user"):
                continue
            br = id_map["branches"].get(r.get("branchId"))
            uid = id_map["users"].get(r["id"])
            if br and uid:
                staff_by_branch[br].append(uid)
        # Ensure every branch has at least one staffer for FK resolution
        for bid, lst in staff_by_branch.items():
            if not lst:
                lst.extend(list(id_map["users"].values())[:1])

        print("Generating classes, students, payments, rentals ...")
        classes = gen_classes(branch_uuids, course_type_id)
        students = gen_students(
            classes, fee_plans_by_licence, promos_by_licence,
            staff_by_branch, students_per_class=10,
        )
        payments, bl_counter = gen_payments(students)
        rentals = gen_rentals(students, vehicles, bl_counter)

        await insert_classes(conn, classes)
        await insert_students(conn, students)
        await insert_payments(conn, payments + rentals)

        # Derive notifications from the payment + class state. Receivers are
        # the responsible staff (or admin fallback). 3 flavors:
        # exam-soon-unpaid, payment_due-30d-zero, document_incomplete.
        from collections import defaultdict
        from decimal import Decimal
        paid_by_student = defaultdict(lambda: Decimal(0))
        for p in payments:  # rentals don't reduce tuition balance
            paid_by_student[p["student_id"]] += p["so_tien"]
        classes_by_id = {c["id"]: c for c in classes}
        admin_uid = next(
            (uid for sid, uid in id_map["users"].items() if sid == "u-admin"),
            list(id_map["users"].values())[0],
        )
        notifications = gen_notifications(
            students, classes_by_id, dict(paid_by_student),
            staff_by_branch, admin_uid,
        )
        await insert_notifications(conn, notifications)

        activity = gen_activity_log(students, classes, payments + rentals, admin_uid)
        await insert_activity_log(conn, activity)

        print("\nSummary:")
        for table in ("branches", "users", "instructors", "vehicles", "fee_plans",
                      "promotions", "classes", "students", "class_enrollments",
                      "payments", "notifications", "audit_logs"):
            n = await conn.fetchval(f"SELECT COUNT(*) FROM {table}")
            print(f"  {table:<22} {n:>6}")
        print("\nLogin: admin@motogiathinh.centersai / admin")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
