"""initial_schema

Revision ID: 30854a990132
Revises: 
Create Date: 2026-05-19 14:46:29.003113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30854a990132'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ma_chi_nhanh', sa.String(length=20), nullable=False),
    sa.Column('ten_chi_nhanh', sa.String(length=200), nullable=False),
    sa.Column('dia_chi', sa.String(length=500), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_chi_nhanh')
    )
    op.create_table('course_types',
    sa.Column('ma_khoa_hoc', sa.String(length=20), nullable=False),
    sa.Column('ten_khoa_hoc', sa.String(length=200), nullable=False),
    sa.Column('loai_bang_lai', sa.Enum('A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F', name='licensetype'), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('so_buoi_ly_thuyet', sa.Integer(), nullable=False),
    sa.Column('so_buoi_thuc_hanh', sa.Integer(), nullable=False),
    sa.Column('tong_gio_hoc', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('thoi_gian_dao_tao', sa.Integer(), nullable=False),
    sa.Column('hoc_phi', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phi_thi', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phi_sat_hach', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tuoi_toi_thieu', sa.SmallInteger(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_khoa_hoc')
    )
    op.create_index(op.f('ix_course_types_loai_bang_lai'), 'course_types', ['loai_bang_lai'], unique=False)
    op.create_table('document_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_sessions',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('ma_ky_thi', sa.String(length=30), nullable=False),
    sa.Column('ten_ky_thi', sa.String(length=200), nullable=False),
    sa.Column('loai_bang_lai', sa.Enum('A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F', name='licensetype'), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=False),
    sa.Column('ngay_thi', sa.Date(), nullable=False),
    sa.Column('gio_bat_dau', sa.Time(), nullable=False),
    sa.Column('gio_ket_thuc', sa.Time(), nullable=False),
    sa.Column('dia_diem_thi', sa.String(length=200), nullable=True),
    sa.Column('phong_thi', sa.String(length=100), nullable=True),
    sa.Column('so_luong_toi_da', sa.Integer(), nullable=False),
    sa.Column('giam_thi', sa.String(length=100), nullable=True),
    sa.Column('co_quan_giam_sat', sa.String(length=200), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('trang_thai', sa.String(length=20), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_ky_thi')
    )
    op.create_index(op.f('ix_exam_sessions_branch_id'), 'exam_sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_loai_bang_lai'), 'exam_sessions', ['loai_bang_lai'], unique=False)
    op.create_index(op.f('ix_exam_sessions_ngay_thi'), 'exam_sessions', ['ngay_thi'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'staff', name='rolename'), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('bien_so', sa.String(length=20), nullable=False),
    sa.Column('loai_xe', sa.String(length=50), nullable=False),
    sa.Column('hang_xe', sa.String(length=100), nullable=True),
    sa.Column('ten_xe', sa.String(length=100), nullable=True),
    sa.Column('nam_san_xuat', sa.SmallInteger(), nullable=True),
    sa.Column('mau_xe', sa.String(length=50), nullable=True),
    sa.Column('so_khung', sa.String(length=50), nullable=True),
    sa.Column('so_may', sa.String(length=50), nullable=True),
    sa.Column('dung_tich_may', sa.SmallInteger(), nullable=True),
    sa.Column('loai_bang_lai', sa.Enum('A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F', name='licensetype'), nullable=False),
    sa.Column('ngay_dang_kiem', sa.Date(), nullable=True),
    sa.Column('ngay_het_dang_kiem', sa.Date(), nullable=True),
    sa.Column('bao_hiem_den_ngay', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.Enum('active', 'maintenance', 'retired', name='vehiclestatus'), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('last_service_km', sa.Integer(), nullable=False),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_km', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('anh_xe_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_bien_so'), 'vehicles', ['bien_so'], unique=True)
    op.create_index(op.f('ix_vehicles_branch_id'), 'vehicles', ['branch_id'], unique=False)
    op.create_index(op.f('ix_vehicles_loai_bang_lai'), 'vehicles', ['loai_bang_lai'], unique=False)
    op.create_index(op.f('ix_vehicles_ngay_het_dang_kiem'), 'vehicles', ['ngay_het_dang_kiem'], unique=False)
    op.create_index(op.f('ix_vehicles_trang_thai'), 'vehicles', ['trang_thai'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=True)
    op.create_table('classes',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('ma_lop', sa.String(length=30), nullable=False),
    sa.Column('ten_lop', sa.String(length=200), nullable=False),
    sa.Column('course_type_id', sa.UUID(), nullable=False),
    sa.Column('ngay_khai_giang', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=True),
    sa.Column('so_luong_toi_da', sa.Integer(), nullable=False),
    sa.Column('so_luong_hien_tai', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('upcoming', 'enrolling', 'in_progress', 'completed', 'cancelled', name='classstatus'), nullable=False),
    sa.Column('phong_hoc', sa.String(length=100), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_types.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_branch_id'), 'classes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_classes_ma_lop'), 'classes', ['ma_lop'], unique=True)
    op.create_index(op.f('ix_classes_trang_thai'), 'classes', ['trang_thai'], unique=False)
    op.create_table('instructors',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ma_giao_vien', sa.String(length=20), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('gioi_tinh', sa.Enum('male', 'female', 'other', name='gendertype'), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=True),
    sa.Column('bang_lai_so', sa.String(length=50), nullable=True),
    sa.Column('ngay_cap_bang', sa.Date(), nullable=True),
    sa.Column('noi_cap_bang', sa.String(length=200), nullable=True),
    sa.Column('ngay_het_han_bang', sa.Date(), nullable=True),
    sa.Column('ngay_vao_lam', sa.Date(), nullable=False),
    sa.Column('ngay_nghi_viec', sa.Date(), nullable=True),
    sa.Column('muc_luong', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_reviews', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('anh_the_url', sa.String(length=500), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_giao_vien')
    )
    op.create_index(op.f('ix_instructors_branch_id'), 'instructors', ['branch_id'], unique=False)
    op.create_index(op.f('ix_instructors_ho_ten'), 'instructors', ['ho_ten'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.Enum('payment_due', 'session_reminder', 'exam_reminder', 'certificate_ready', 'document_incomplete', name='notiftrigger'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_status', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('ma_hoc_vien', sa.String(length=20), nullable=False),
    sa.Column('ten_hoc_vien', sa.String(length=100), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('gioi_tinh', sa.Enum('male', 'female', 'other', name='gendertype'), nullable=False),
    sa.Column('cccd_number', sa.String(length=20), nullable=True),
    sa.Column('cccd_issued_date', sa.Date(), nullable=True),
    sa.Column('cccd_issued_place', sa.String(length=200), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=False),
    sa.Column('dia_chi_email', sa.String(length=255), nullable=True),
    sa.Column('dia_chi', sa.Text(), nullable=True),
    sa.Column('phuong_xa', sa.String(length=100), nullable=True),
    sa.Column('quan_huyen', sa.String(length=100), nullable=True),
    sa.Column('tinh_thanh', sa.String(length=100), nullable=True),
    sa.Column('ho_ten_nguoi_than', sa.String(length=100), nullable=True),
    sa.Column('sdt_nguoi_than', sa.String(length=20), nullable=True),
    sa.Column('quan_he', sa.String(length=50), nullable=True),
    sa.Column('loai_bang_lai', sa.Enum('A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F', name='licensetype'), nullable=False),
    sa.Column('trang_thai', sa.Enum('pending', 'active', 'suspended', 'completed', 'dropped', name='studentstatus'), nullable=False),
    sa.Column('is_repeat_student', sa.Boolean(), nullable=False),
    sa.Column('repeat_count', sa.SmallInteger(), nullable=False),
    sa.Column('lead_source', sa.Enum('facebook', 'walk_in', 'referral', 'zalo', 'chatbot', 'other', name='leadsource'), nullable=True),
    sa.Column('facebook_lead_id', sa.String(length=100), nullable=True),
    sa.Column('anh_the_url', sa.String(length=500), nullable=True),
    sa.Column('cmnd_front_url', sa.String(length=500), nullable=True),
    sa.Column('cmnd_back_url', sa.String(length=500), nullable=True),
    sa.Column('health_cert_url', sa.String(length=500), nullable=True),
    sa.Column('health_cert_expiry', sa.Date(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('zalo_number', sa.String(length=20), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('ngay_dang_ky', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_branch_id'), 'students', ['branch_id'], unique=False)
    op.create_index(op.f('ix_students_cccd_number'), 'students', ['cccd_number'], unique=True)
    op.create_index(op.f('ix_students_loai_bang_lai'), 'students', ['loai_bang_lai'], unique=False)
    op.create_index(op.f('ix_students_ma_hoc_vien'), 'students', ['ma_hoc_vien'], unique=True)
    op.create_index(op.f('ix_students_so_dien_thoai'), 'students', ['so_dien_thoai'], unique=False)
    op.create_index(op.f('ix_students_ten_hoc_vien'), 'students', ['ten_hoc_vien'], unique=False)
    op.create_index(op.f('ix_students_trang_thai'), 'students', ['trang_thai'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('vehicle_maintenance',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_center', sa.String(length=200), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('next_due_km', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenance_vehicle_id'), 'vehicle_maintenance', ['vehicle_id'], unique=False)
    op.create_table('class_enrollments',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ly_thuyet_status', sa.String(length=20), nullable=False),
    sa.Column('thuc_hanh_status', sa.String(length=20), nullable=False),
    sa.Column('overall_progress', sa.SmallInteger(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id')
    )
    op.create_index(op.f('ix_class_enrollments_class_id'), 'class_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_student_id'), 'class_enrollments', ['student_id'], unique=False)
    op.create_table('instructor_availability',
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instructor_id', 'day_of_week', 'start_time')
    )
    op.create_table('leads',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('ho_ten', sa.String(length=100), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('lead_source', sa.Enum('facebook', 'walk_in', 'referral', 'zalo', 'chatbot', 'other', name='leadsource'), nullable=False),
    sa.Column('facebook_lead_id', sa.String(length=100), nullable=True),
    sa.Column('facebook_page_id', sa.String(length=100), nullable=True),
    sa.Column('ad_name', sa.String(length=200), nullable=True),
    sa.Column('form_name', sa.String(length=200), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trang_thai', sa.Enum('new', 'contacted', 'enrolled', 'lost', 'unclaimed', name='leadstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('converted_to', sa.UUID(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['converted_to'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_branch_id'), 'leads', ['branch_id'], unique=False)
    op.create_index(op.f('ix_leads_facebook_lead_id'), 'leads', ['facebook_lead_id'], unique=True)
    op.create_index(op.f('ix_leads_so_dien_thoai'), 'leads', ['so_dien_thoai'], unique=False)
    op.create_index(op.f('ix_leads_trang_thai'), 'leads', ['trang_thai'], unique=False)
    op.create_table('sessions',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.Enum('theory', 'practice', 'exam_prep', name='sessiontype'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('dia_diem', sa.String(length=200), nullable=True),
    sa.Column('phong_hoc', sa.String(length=100), nullable=True),
    sa.Column('noi_dung', sa.Text(), nullable=True),
    sa.Column('tai_lieu_url', sa.String(length=500), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_branch_id'), 'sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sessions_class_id'), 'sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_sessions_instructor_id'), 'sessions', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_date'), 'sessions', ['session_date'], unique=False)
    op.create_table('student_documents',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('doc_type_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('ocr_raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_student_id'), 'student_documents', ['student_id'], unique=False)
    op.create_table('student_health_checks',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('vision_left', sa.String(length=10), nullable=True),
    sa.Column('vision_right', sa.String(length=10), nullable=True),
    sa.Column('hearing_result', sa.String(length=50), nullable=True),
    sa.Column('overall_result', sa.String(length=20), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_health_checks_student_id'), 'student_health_checks', ['student_id'], unique=False)
    op.create_table('attendance',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('trang_thai', sa.Enum('present', 'absent', 'late', 'excused', name='attendancestatus'), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id')
    )
    op.create_index(op.f('ix_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('exam_registrations',
    sa.Column('exam_session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_enrollment_id', sa.UUID(), nullable=True),
    sa.Column('ket_qua', sa.Enum('pass_', 'fail', 'absent', 'pending', name='examresult'), nullable=False),
    sa.Column('diem_ly_thuyet', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('diem_thuc_hanh', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('diem_luat_gt', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('so_lan_thi', sa.SmallInteger(), nullable=False),
    sa.Column('so_bao_danh', sa.String(length=20), nullable=True),
    sa.Column('chung_chi_thi_url', sa.String(length=500), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_enrollment_id'], ['class_enrollments.id'], ),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_session_id', 'student_id')
    )
    op.create_index(op.f('ix_exam_registrations_exam_session_id'), 'exam_registrations', ['exam_session_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_student_id'), 'exam_registrations', ['student_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_enrollment_id', sa.UUID(), nullable=False),
    sa.Column('payment_type', sa.Enum('full', 'installment', 'waived', name='paymenttypeenum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_reason', sa.String(length=200), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'waived', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['class_enrollment_id'], ['class_enrollments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plans_branch_id'), 'payment_plans', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_payment_status'), 'payment_plans', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_plans_student_id'), 'payment_plans', ['student_id'], unique=False)
    op.create_table('session_logs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('noi_dung_giang', sa.Text(), nullable=True),
    sa.Column('ket_qua', sa.Text(), nullable=True),
    sa.Column('issues_noted', sa.Text(), nullable=True),
    sa.Column('odometer_start', sa.Integer(), nullable=True),
    sa.Column('odometer_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('certificates',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('exam_registration_id', sa.UUID(), nullable=True),
    sa.Column('loai_bang_lai', sa.Enum('A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F', name='licensetype'), nullable=False),
    sa.Column('so_chung_chi', sa.String(length=50), nullable=True),
    sa.Column('ngay_cap', sa.Date(), nullable=True),
    sa.Column('noi_cap', sa.String(length=200), nullable=True),
    sa.Column('ngay_het_han', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.Enum('pending', 'issued', 'submitted_to_authority', 'revoked', name='certificatestatus'), nullable=False),
    sa.Column('ngay_nop_ho_so', sa.Date(), nullable=True),
    sa.Column('so_bien_lai_nop', sa.String(length=50), nullable=True),
    sa.Column('du_kien_co_bang', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_registration_id'], ['exam_registrations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_chung_chi')
    )
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_index(op.f('ix_certificates_trang_thai'), 'certificates', ['trang_thai'], unique=False)
    op.create_table('payments',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('payment_plan_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('ma_giao_dich', sa.String(length=50), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phuong_thuc', sa.Enum('cash', 'bank_transfer', 'momo', 'zalopay', name='paymentmethod'), nullable=False),
    sa.Column('loai_thanh_toan', sa.String(length=50), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ma_tham_chieu', sa.String(length=100), nullable=True),
    sa.Column('ngan_hang', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'waived', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('so_bien_lai', sa.String(length=50), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_branch_id'), 'payments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payments_collected_by'), 'payments', ['collected_by'], unique=False)
    op.create_index(op.f('ix_payments_ma_giao_dich'), 'payments', ['ma_giao_dich'], unique=True)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_plan_id'), 'payments', ['payment_plan_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('payment_gateway_logs',
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_gateway_logs')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_ma_giao_dich'), table_name='payments')
    op.drop_index(op.f('ix_payments_collected_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_branch_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_certificates_trang_thai'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_table('session_logs')
    op.drop_index(op.f('ix_payment_plans_student_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_payment_status'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_branch_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_exam_registrations_student_id'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_exam_session_id'), table_name='exam_registrations')
    op.drop_table('exam_registrations')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_student_health_checks_student_id'), table_name='student_health_checks')
    op.drop_table('student_health_checks')
    op.drop_index(op.f('ix_student_documents_student_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_sessions_session_date'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_instructor_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_class_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_branch_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_leads_trang_thai'), table_name='leads')
    op.drop_index(op.f('ix_leads_so_dien_thoai'), table_name='leads')
    op.drop_index(op.f('ix_leads_facebook_lead_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_branch_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('instructor_availability')
    op.drop_index(op.f('ix_class_enrollments_student_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_class_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_vehicle_maintenance_vehicle_id'), table_name='vehicle_maintenance')
    op.drop_table('vehicle_maintenance')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_students_trang_thai'), table_name='students')
    op.drop_index(op.f('ix_students_ten_hoc_vien'), table_name='students')
    op.drop_index(op.f('ix_students_so_dien_thoai'), table_name='students')
    op.drop_index(op.f('ix_students_ma_hoc_vien'), table_name='students')
    op.drop_index(op.f('ix_students_loai_bang_lai'), table_name='students')
    op.drop_index(op.f('ix_students_cccd_number'), table_name='students')
    op.drop_index(op.f('ix_students_branch_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_instructors_ho_ten'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_branch_id'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_classes_trang_thai'), table_name='classes')
    op.drop_index(op.f('ix_classes_ma_lop'), table_name='classes')
    op.drop_index(op.f('ix_classes_branch_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicles_trang_thai'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_ngay_het_dang_kiem'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_loai_bang_lai'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_branch_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_bien_so'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exam_sessions_ngay_thi'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_loai_bang_lai'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_branch_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_course_types_loai_bang_lai'), table_name='course_types')
    op.drop_table('course_types')
    op.drop_table('branches')
    # ### end Alembic commands ###
