export const themeTokens = {
  dark: {
    '--mgt-bg-base': '#0d1117',
    '--mgt-bg-container': '#161b22',
    '--mgt-bg-elevated': '#1c2128',
    '--mgt-bg-hover': '#1d2a3a',
    '--mgt-bg-success': '#12261e',
    '--mgt-bg-warning': '#1c1608',
    '--mgt-border': '#21262d',
    '--mgt-border-strong': '#30363d',
    '--mgt-text-primary': '#f0f6fc',
    '--mgt-text-body': '#c9d1d9',
    '--mgt-text-secondary': '#8b949e',
    '--mgt-gradient-card': 'linear-gradient(135deg, #0d1117, #161b22)',
    '--mgt-gradient-login': 'linear-gradient(135deg, #161b22, #0d1117)',
    '--mgt-accent-primary': '#1677ff',
    '--mgt-accent-primary-hover': '#4096ff',
    '--mgt-accent-success': '#52c41a',
    '--mgt-accent-warning': '#f5a623',
    '--mgt-accent-danger': '#ff4d4f',
    '--mgt-tag-blue-bg': '#1d2a3a',
    '--mgt-tag-blue-border': 'rgba(22,119,255,0.25)',
    '--mgt-tag-blue-text': '#4096ff',
    '--mgt-tag-green-bg': '#12261e',
    '--mgt-tag-green-border': 'rgba(82,196,26,0.19)',
    '--mgt-tag-green-text': '#52c41a',
  },
  light: {
    '--mgt-bg-base': '#f5f5f5',
    '--mgt-bg-container': '#ffffff',
    '--mgt-bg-elevated': '#ffffff',
    '--mgt-bg-hover': '#e6f4ff',
    '--mgt-bg-success': '#f6ffed',
    '--mgt-bg-warning': '#fffbe6',
    '--mgt-border': '#d9d9d9',
    '--mgt-border-strong': '#bfbfbf',
    '--mgt-text-primary': '#141414',
    '--mgt-text-body': '#262626',
    '--mgt-text-secondary': '#595959',
    '--mgt-gradient-card': 'linear-gradient(135deg, #ffffff, #fafafa)',
    '--mgt-gradient-login': 'linear-gradient(135deg, #ffffff, #f5f5f5)',
    '--mgt-accent-primary': '#1677ff',
    '--mgt-accent-primary-hover': '#4096ff',
    '--mgt-accent-success': '#52c41a',
    '--mgt-accent-warning': '#f5a623',
    '--mgt-accent-danger': '#ff4d4f',
    '--mgt-tag-blue-bg': '#e6f4ff',
    '--mgt-tag-blue-border': '#91caff',
    '--mgt-tag-blue-text': '#1677ff',
    '--mgt-tag-green-bg': '#f6ffed',
    '--mgt-tag-green-border': '#b7eb8f',
    '--mgt-tag-green-text': '#52c41a',
  },
} as const

export const antdTokens = {
  dark: {
    colorBgBase: '#0d1117',
    colorBgContainer: '#161b22',
    colorBorder: '#30363d',
    colorText: '#f0f6fc',
    colorTextSecondary: '#8b949e',
  },
  light: {
    colorBgBase: '#f5f5f5',
    colorBgContainer: '#ffffff',
    colorBorder: '#d9d9d9',
    colorText: '#141414',
    colorTextSecondary: '#595959',
  },
}
